site_name: UNLV MR Imaging Core

theme:
  name: material
  logo: assets/unlvreverse.png
  palette:
    primary: custom
  features:
    - navigation.sections

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - New Users: new-users.md

  - Training: training.md

  - Screening Process: screening.md

  - MRI Prisma 3T: prisma.md

  - Phlebotomy: prisma.md

  - Safety: safety.md
     
  - Policies: policies.md

  - Pricing & Parking: pricing.md

  - News: news.md

  - Contact & Directions: contact.md

markdown_extensions:
  - toc:
      permalink: false
  - attr_list
  - admonition
  - pymdownx.details
